dist: xenial
language: node_js
node_js:
  - "12"
cache:
  npm: true
  directories:
    - node_modules
addons:
  apt:
    packages:
      - subversion
install:
  - npm install
  - node build.js
script:
  - jest --coverage
  - jshint ./src
  - cat ./coverage/lcov.info | coveralls