[options.placing]
diagonals = false

[options.rendering.icons]
color = "#00695C"

[options.rendering.links]
color = "#26A69A"

[options.rendering.texts]
color = "#004D40"
font = "mono"
font-size = 12
margin = 0.25

[options.rendering.sub-icons]
color = "#004D40"

[[nodes]]
name = "client"
icon = "laptop"
bottom = "user"

[[nodes]]
name = "page"
icon = "file-code"
top = "index.html"

[[nodes]]
name = "js"
icon = "js-square"
bottom = "front-end"

[[nodes]]
name = "server"
icon = "node"
bottom = "back-end"

[[nodes]]
name = "db"
icon = "database"

[[links]]
from = "client"
to = "page"

[[links]]
from = "page"
to = "js"
type = "double"
bottom = "VueJS"
direction = "down"

  [links.top]
  icon = "vuejs"

[[links]]
from = "js"
to = "server"
type = "split-double"
direction = "right"

  [links.top]
  text = "Ajax"

  [links.bottom]
  text = "JSON"

[[links]]
from = "db"
to = "server"
type = "double"
bottom = "Sequelize"
